version: "3.5"

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    expose:
      - "3306"
    restart: always
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception-net
    env_file:
      - .env

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    expose:
      - "9000"
    restart: always
    volumes:
      - wp:/var/www/html
    depends_on :
      - mariadb
    networks:
      - inception-net
    env_file:
      - .env

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx
    ports:
      - 443:443
    restart: always
    volumes:
      - wp:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception-net

  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - inception-net
    restart: always

  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    depends_on:
      - mariadb
    image: adminer
    ports:
      - "8080:8080"
    networks:
     - inception-net
    restart: always

  flask:
    build: ./requirements/bonus/flask
    container_name: flask
    image: flask
    ports:
      - "5000:5000"
    restart: always


volumes:
  wp:
    name: wp
    driver: local
    driver_opts:
      type: volume
      device: /home/taehykim/data/wp
      o: bind
  db:
    name: db
    driver: local
    driver_opts:
      type: volume
      o: bind
      device: /home/taehykim/data/db

networks:
  inception-net:
    driver: bridge
