version: '2'
services:
    mariadb:
			  ...

    wordpress:
  			...

    nginx:
 			  ...

volumes:
    mariadb:
 			  ...

    wordpress:
 			  ...   

networks:
    inception:
        driver: bridge