CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'tae'@'%' IDENTIFIED BY 'tae1234';
GRANT ALL PRIVILEGES ON wordpress.* TO 'tae'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY '1234';